### ISSUE TITLE
note to self (or someone with a spare 5 mins)

### ISSUE THREAD

**Issue by ngood13** [ngood13/stoves_nih_2016_git#106]
update ecoc.Rmd and voc.Rmd to output class _tibble_

**Comment by kbilsback** [comment]
Are you talking about changing the data frames to tibbles within the code (i.e. as_tibble) or how the markdown prints data frames (i.e. tibble::print.tbl_df rather than knitr::kable)?

**Comment by ngood13** [comment]
changing the data frames to tibbles in their respective pollutant specific markdowns

**Comment by kbilsback** [comment]
Done in manuscript_kb branch
