### ISSUE TITLE
emission_factors.Rmd

### ISSUE THREAD

**Issue by ngood13** [ngood13/stoves_nih_2016_git#111]
file requires review and more work

**Comment by kbilsback** [comment]
@ngood13 currently all the five gas variables have NA for the background concentration, is that a bug or is it supposed to be like that for real-time instruments?

**Comment by nickgood** [comment]
Good spot Kelsey!

The bug is in “emissions_pol.Rmd” line 426. You’ll see conc_bg is missing from the co_co2_ch4 select function. Do you want to open a branch and fix this? FYI the background is accounted for in the code above...

**Comment by kbilsback** [comment]
- Also, what was the reason ultra fines were coming through from emissions_pol again?
- Finally, it looks like we have a bunch of NA backgrounds for real-time instruments, which are causing pollutant values to be NA. Need to see if we can't find a way to estimate the background.

**Comment by ngood13** [comment]
Ultra-fines -  Because they are an emitted pollutant??? (I think I'm not understanding the question) 🐠

**Comment by kbilsback** [comment]
Ahhh I meant to say why are they NOT coming through.... 🙊🙈🍒

Is this just a bug I should be fixing

**Comment by ngood13** [comment]
re - missing fivegas backgrounds:

You can replace the code chunk at line 214 with this:

The code is meant to replace missing values with the mean of the good values, because NAs are now being removed prior, they were not added... This should fix it:

``
  bg_co <- dplyr::left_join(dplyr::select(samples, id), bg_co) %>%
           dplyr::mutate(ppm_bg = ifelse(is.na(ppm), bg_co_mean$ppm[1], ppm),
                         conc_bg = ifelse(is.na(conc), bg_co_mean$conc[1], conc),
                         pol = "co")

  bg_co2 <- dplyr::left_join(dplyr::select(samples, id), bg_co2) %>%
           dplyr::mutate(ppm_bg = ifelse(is.na(ppm), bg_co2_mean$ppm[1], ppm),
                         conc_bg = ifelse(is.na(conc), bg_co2_mean$conc[1], conc),
                         pol = "co2")

  bg_ch4 <- dplyr::left_join(dplyr::select(samples, id), bg_ch4) %>%
            dplyr::mutate(ppm_bg = ifelse(is.na(ppm), bg_ch4_mean$ppm[1], ppm),
                          conc_bg = ifelse(is.na(conc), bg_ch4_mean$conc[1], conc),
                          pol = "ch4")

  bg <- dplyr::bind_rows(bg_co, bg_co2, bg_ch4)
``

**Comment by ngood13** [comment]
ha ha, you're as bad as me sometimes 🐒

re: smps - you mean the smps data isn't being written to "emissions.Rda"? This is because the columns don't line up. You could add code to write a standalone smps emissions .Rda file for now? E.g. emissions_ultrafines.Rda

**Comment by kbilsback** [comment]
Ewwww it would be so irritating to mess with our beautiful emissions.Rda symmetry though 🐫🐪

**Comment by nickgood** [comment]
One option is to make the data longer -> var, val, units instead of columns for mass_emitted, conc …..

**Comment by kbilsback** [comment]
oooooooo I really like that idea, that way we can be more consistent about units throughout

**Comment by kbilsback** [comment]
👏

**Comment by nickgood** [comment]
Got for it! Something like (with a better output object name!):

  df_long <- tidyr::gather(df, "units", "value", conc,
                                            mass_emitted,
                                            mass_carbon,
                                            conc_bg)

**Comment by kbilsback** [comment]
header should be:
id, pol, val, units, metric qc, in "emissions_factors" 
see update in master_kb branch
