### ISSUE TITLE
Negative values

### ISSUE THREAD

**Issue by kbilsback** [ngood13/stoves_nih_2016_git#114]
`> filter(emissions, conc <= 0)
# A tibble: 2 × 12
     id   pol      conc   conc_bg mass_emitted mass_carbon    inst    qc   mass_ef mass_c_ef energy_ef
  <chr> <chr>     <dbl>     <dbl>        <dbl>       <dbl>   <chr> <chr>     <dbl>     <dbl>     <dbl>
1   15A   ch4 -14190.21 -17631.15    1013931.5    759104.0 fivegas    ok 1131.3675 382067.34  19.80006
2    9A   ch4 -12770.77 -16680.06     761008.8    569747.3 fivegas    ok  837.1933   1121.76  14.65172
# ... with 1 more variables: energy_c_ef <dbl>`

**Comment by ngood13** [comment]
see email

**Comment by kbilsback** [comment]
Note to self: update code to take next nearest calibration date

**Comment by nickgood** [comment]
What are we doing now? I think taking the calibration prior to the test is the way to do. Which  assume is what I would have tried to do?

---

Nicholas Good, BSc. PhD.
Scott Building
Department of Mechanical Engineering
Colorado State University
Fort Collins
Colorado
80523-1301

Tel: +1.970.491.7607
Alt: +1.970.310.3750
Email: n.good@colostate.edu<mailto:n.good@colostate.edu>

On Mar 1, 2017, at 18:56, Kelsey <notifications@github.com<mailto:notifications@github.com>> wrote:


Note to self: update code to take next nearest calibration date

**Comment by kbilsback** [comment]
fixed (master_kb)
