### ISSUE TITLE
NA and NaN inconsistencies 

### ISSUE THREAD

**Issue by kbilsback** [ngood13/stoves_nih_2016_git#115]
i.e. emissions.Rda

**Comment by ngood13** [comment]
Think these occur when files are loaded / saved? Look to see what data looks like before saving and after loading...

**Comment by kbilsback** [comment]
That's what I figured. Could be as simple as replacing when files are loaded.

**Comment by kbilsback** [comment]
I've been following your virtuous path and using our issues page as a note to self 😸 :octocat: 🎿

**Comment by ngood13** [comment]
A truly noble approach!

**Comment by kbilsback** [comment]
Use RDSs

**Comment by kbilsback** [comment]
note to self this still a problem....go back and fix

**Comment by kbilsback** [comment]
fixed (in master_kb)
