### ISSUE TITLE
Missing five gas data

### ISSUE THREAD

**Issue by kbilsback** [ngood13/stoves_nih_2016_git#116]
Need to explore missing fivegas data from emissions.Rda. It looks like data from 18 five gas data isn't coming through. We only report missing from two tests and mark six as bad (also need to look into why they are marked bad - looks like visual inspection).

**Comment by ngood13** [comment]
Can you check if these are the tests logged using voltage...? We had something similar before. There are about 4 fivegas file formats. So could be something like voltage/military time files are failing... Thought I'd sorted this, could be a bad merge overwrote the update...

**Comment by kbilsback** [comment]
Maybe...? Here's the breakdown: 

8C - Mixing ratios
8A - Voltage
6A - Voltage
6C - Mixing ratios
4A - No file
4B -  Marked as bad
3A - Voltage
2C - Mixing ratios
23B -  Marked as bad
23A - Mixing ratios
21C - Mixing ratios
20A - Voltage
1A - Voltage
1B - No data
18C - Marked as bad
17C - Marked as bad
17B - Voltage
13A - Voltage

**Comment by ngood13** [comment]
Are all those files marked as bad or maybe? Take a look at the fivegas.html. I think they might be?

**Comment by kbilsback** [comment]
Hmmm some are but some aren't if it was a qc designation problem, this list should include all the maybes...

**Comment by ngood13** [comment]
Umm, looking at the plot, I’m pretty sure this list has all the maybes?

**Comment by kbilsback** [comment]
But shouldn't either all maybes or no maybes be filtered out? I'm saying not ALL maybe's are on the list.

**Comment by kbilsback** [comment]
all accounted for see: https://docs.google.com/spreadsheets/d/1Qz-DpA2MW_NJEwMQ9DafKFKWdPQ-6n6b3r9Ep3A_MYs/edit?usp=drive_web&ouid=109674984548566211258
