### ISSUE TITLE
List of abbreviations/terms

### ISSUE THREAD

**Issue by tcolehunter** [ngood13/stoves_nih_2016_git#25]
Have you guys been recording coding/names or just know them from meeting face-to-face?

**Comment by ngood13** [comment]
We have several very much living google docs we can share, just mail be an address. Hopefully the .Rmd's are easy to follow without too much additional documentation (that is the idea anyway).

**Comment by tcolehunter** [comment]
HI Nick,

My Gmail address for GDoc access is tcolehunter@gmail.com<mailto:tcolehunter@gmail.com>

Cheers!
