### ISSUE TITLE
Reverting commit: HTML upload

### ISSUE THREAD

**Issue by tcolehunter** [ngood13/stoves_nih_2016_git#53]
@ngood13 - has reverting my commit of uploading the `.rmd` and `.html` files removed them from GitHub?

**Comment by KFedak** [comment]
no it does not. I just deleted the co html from your branch manually within the github page. If there are others please go into github, select them, and find the delete trash can to manually remove them!

**Comment by tcolehunter** [comment]
Oh, I could not see a way of just deleting from the branch on here - thanks for doing that - there are no others to be deleted.

**Comment by KFedak** [comment]
When you click on the file, there is a trash can symbol along the top right
