### ISSUE TITLE
Negative emissions values

### ISSUE THREAD

**Issue by kbilsback** [ngood13/stoves_nih_2016_git#57]
> sum(emissions$mass_emitted < 0, na.rm = TRUE)
[1] 228

**Comment by ngood13** [comment]
We should revisit this table, some time this week and see what's still looking suspicious!

**Comment by ngood13** [comment]
Looks like this is much better now? Some ion/vocs/carbonyls with concentrations below background, also 3 or so gravimetric data points.

**Comment by kbilsback** [comment]
Hmmm, 16C from the gravimetric values seems low, I will add to outlier google spread sheet. Also it seems like there are quite a few vocs/ions/carbonyls that are negative. Probably ok though.

**Comment by nickgood** [comment]
Yeah, I think these all come from when the measured value is below background...

**Comment by kbilsback** [comment]
Negative 16C was due to a transcription error. It's fixed in the original file on the server now.
