### ISSUE TITLE
Is there something that I can do to help become more familiar with this process of pushing, pulling, etc?

### ISSUE THREAD

**Issue by tcolehunter** [ngood13/stoves_nih_2016_git#65]
Anything small that needs to be done and doesn't require knowledge of the testing?

I'd like to be useful... :1234:

**Comment by ngood13** [comment]
We could use an estimate of our transcription error. I'd pick two random batch and wood tests and compare the written notes to the logs. Second a plot showing the relationship between ec/oc concentration and ug_sq_cm  (as a function of: sample duration and flow rate) would be a useful addition to the ecoc markdown, contained to values used / measured during the study, perhaps something similar to what we did for the aethalometer analysis (https://www.mendeley.com/research/accurate-filter-loading-correction-essential-assessing-personal-exposure-black-carbon-using-aethalom/)

**Comment by tcolehunter** [comment]
I'd be happy to try that, @nickgood. If I get stuck, when are you next in the Powerhouse prior to Friday's meeting?

Meanwhile, could you please send me the PDF of that JESEE article you've linked above? I'm being told that (while on the CSU network) I don't have institution access... does that sound right?

**Comment by ngood13** [comment]
Emailed

**Comment by tcolehunter** [comment]
Hi @ngood13 - to which address? I haven't received anything yet... could you please try again?

**Comment by nickgood** [comment]
@colstate, tried again...
---

Nicholas Good, BSc. PhD.
Scott Building
Department of Mechanical Engineering
Colorado State University
Fort Collins
Colorado
80523-1301

Tel: +1.970.491.7607
Alt: +1.970.310.3750
Email: n.good@colostate.edu<mailto:n.good@colostate.edu>

On Feb 15, 2017, at 08:44, Tom Cole-Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @ngood13<https://github.com/ngood13> - to which address? I haven't received anything yet... could you please try again?
