### ISSUE TITLE
The most important issue yet!

### ISSUE THREAD

**Issue by ngood13** [ngood13/stoves_nih_2016_git#71]
We need a consistent qc flag color scale to apply across all rmds:

http://sape.inf.usi.ch/quick-reference/ggplot2/colour

scale_colour_manual(values = c("ok" = "chartreuse4",
                                   "maybe" = "dodgerblue2",
                                   "bad" = "springgreen3"))

add your suggestions

**Comment by kbilsback** [comment]
I vote for 
ok = mediumorchid 
maybe = mediumaquamarine
bad = mistyrose4 (or go crazy and just make it black?)

I'm also a fan of slateblue and the various seagreens.

**Comment by kbilsback** [comment]
Also, dogerblue is okay, but chartreuse4 & springgreen3 --- :)

**Comment by ngood13** [comment]
Do you think the "green" should be good? Otherwise I worry its not intuitive?

**Comment by kbilsback** [comment]
Fine, but being intuitive is boring! Can we make maybe purple at least? and maybe bad black?

**Comment by tcolehunter** [comment]
To continue the "being boring" / intuitive trend, could we use traffic light colours: OK = green; maybe = amber/yellow/orange(/whatever-colour-the-middle-light-is); bad = red. These coloured fonts especially 'pop' when using a black background for high contrast.

That's my two cents :1st_place_medal: :1st_place_medal:

**Comment by ngood13** [comment]
Thanks everyone!
