### ISSUE TITLE
branch cleanup 

### ISSUE THREAD

**Issue by kbilsback** [ngood13/stoves_nih_2016_git#86]
@tcolehunter In order to keep our github page organized, typically branches are only created/used for a short period of time until a specific task is accomplished and then deleted. Can you take a look at your branches and delete them if you think those tasks are accomplished? (i.e. "tcolehunter-test-co-1" and "co_descrip").

**Comment by tcolehunter** [comment]
Thanks @kbilsback for letting this be known. Old, redundant/unneeded branches of mine have been deleted.
