### ISSUE TITLE
Outlier Investigations

### ISSUE THREAD

**Issue by KFedak** [ngood13/stoves_nih_2016_git#89]
Hi! 

I finished going through the list of outliers on the google doc and going through the "process metadata" html file. :1st_place_medal:  

All outliers that were results of transcription errors have been fixed within the respective logs on the server - so these should be re-loaded into new .Rda files and pulled through the process. I have a few red highlighted cells on the outliers google doc to bring attention to a few issues that I wasn't sure how/where to address... :confused: maybe we can talk about these on Monday...

@ngood13 - I was having a weird saving issue with the "Transcribed wood sampling form" and so the MOST current version is saved with my initials at the end. For some reason I wasn't able to save over the other version, or move the other version to the archive folder...so you'll want to  adjust this before you try to recreate the data files. 

Now back to my prelim proposal...

**Comment by ngood13** [comment]
Great! I’ll take a look at this in the morning. Hope the proposal is going well!

**Comment by ngood13** [comment]
Merged! Yes, let's discuss outstanding items tomorrow...
